name: nb_solutions
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lottie:
  get: ^4.6.6
  flutter_keyboard_visibility: ^6.0.0
  firebase_core: ^3.0.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  flutter_easyloading: ^3.0.5
  firebase_messaging: ^15.0.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  image_card: ^0.0.4
  flutter_swipe_action_cell: ^3.1.2
  url_launcher: ^6.2.1
  firebase_analytics: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
