// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAluqbvnU6bSW3TMrDvlaW6DPh32WjKRLo',
    appId: '1:405678533869:web:04245d788d7bd499e3b0e4',
    messagingSenderId: '405678533869',
    projectId: 'nbsolutions-1e5cc',
    authDomain: 'nbsolutions-1e5cc.firebaseapp.com',
    storageBucket: 'nbsolutions-1e5cc.appspot.com',
    measurementId: 'G-MGQ7WB1ZGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc4U1D7OfqvF-zrNIhghc55Ov-wMqwWpY',
    appId: '1:405678533869:android:e6cf976e945aef41e3b0e4',
    messagingSenderId: '405678533869',
    projectId: 'nbsolutions-1e5cc',
    storageBucket: 'nbsolutions-1e5cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAesH2kITOcAcBTbqDmDr0SMyZXDLSxkN0',
    appId: '1:405678533869:ios:bfc702a857c27b3fe3b0e4',
    messagingSenderId: '405678533869',
    projectId: 'nbsolutions-1e5cc',
    storageBucket: 'nbsolutions-1e5cc.appspot.com',
    androidClientId: '405678533869-votjk3h2jkvlp8103u70lr6uolrcvmev.apps.googleusercontent.com',
    iosClientId: '405678533869-2hdnef0e1lmu15qrvn1ir2d89s5f3rmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.nbSolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAesH2kITOcAcBTbqDmDr0SMyZXDLSxkN0',
    appId: '1:405678533869:ios:bfc702a857c27b3fe3b0e4',
    messagingSenderId: '405678533869',
    projectId: 'nbsolutions-1e5cc',
    storageBucket: 'nbsolutions-1e5cc.appspot.com',
    androidClientId: '405678533869-votjk3h2jkvlp8103u70lr6uolrcvmev.apps.googleusercontent.com',
    iosClientId: '405678533869-2hdnef0e1lmu15qrvn1ir2d89s5f3rmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.nbSolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAluqbvnU6bSW3TMrDvlaW6DPh32WjKRLo',
    appId: '1:405678533869:web:a174d383b90cf5a7e3b0e4',
    messagingSenderId: '405678533869',
    projectId: 'nbsolutions-1e5cc',
    authDomain: 'nbsolutions-1e5cc.firebaseapp.com',
    storageBucket: 'nbsolutions-1e5cc.appspot.com',
    measurementId: 'G-RZSLEDEPFN',
  );
}
